import type { ShippingMode } from "@/data/shipping";

/**
 * Order item representing a product variant in an order.
 * Based on CartItem but simplified for order storage.
 */
export type OrderItem = {
  /** Product ID */
  id: string;
  /** Product slug */
  slug: string;
  /** Product name (French) */
  name: string;
  /** Unit price in DZD */
  price: number;
  /** Currency code */
  currency: string;
  /** Product image URL */
  image: string;
  /** Color name (French) */
  colorName: string;
  /** Color code/ID */
  colorCode: string;
  /** Selected size */
  size: string;
  /** Quantity ordered */
  quantity: number;
  /** Variant key for uniqueness (id-colorCode-size) */
  variantKey: string;
};

/**
 * Shipping information for an order.
 */
export type ShippingInfo = {
  /** Customer full name */
  customerName: string;
  /** Customer phone number */
  phone: string;
  /** Delivery wilaya (Algerian province) */
  wilaya: string;
  /** Delivery address */
  address: string;
  /** Delivery mode: "home" (à domicile) or "desk" (Stop Desk) */
  mode: ShippingMode;
  /** Shipping cost in DZD */
  price: number;
};

/**
 * Order status lifecycle.
 */
export type OrderStatus =
  | "pending" // Order placed, awaiting confirmation
  | "confirmed" // Order confirmed, preparing for shipment
  | "shipped" // Order shipped
  | "delivered" // Order delivered
  | "cancelled"; // Order cancelled

/**
 * Payment method used for the order.
 */
export type PaymentMethod = "COD"; // Cash on Delivery (currently only method)

/**
 * Complete order definition stored in Firestore.
 */
export type Order = {
  /** Unique order ID (generated by Firestore or UUID) */
  id: string;
  /** Customer email address */
  customerEmail: string;
  /** Order items (product variants) */
  items: OrderItem[];
  /** Shipping information */
  shipping: ShippingInfo;
  /** Customer notes (optional) */
  notes?: string;
  /** Subtotal (sum of item prices * quantities) */
  subtotal: number;
  /** Shipping cost */
  shippingCost: number;
  /** Grand total (subtotal + shipping) */
  total: number;
  /** Payment method */
  paymentMethod: PaymentMethod;
  /** Order status */
  status: OrderStatus;
  /** ISO timestamp when order was created */
  createdAt: string;
  /** ISO timestamp when order was last updated */
  updatedAt: string;
  /** ISO timestamp when order was cancelled (if applicable) */
  cancelledAt?: string;
};

/**
 * Order data for creating a new order (without generated fields).
 */
export type NewOrder = Omit<Order, "id" | "createdAt" | "updatedAt">;
